/* eslint-disable */
// Generated by Wrangler by running `wrangler types refresh-worker/worker-configuration.d.ts --config refresh-worker/wrangler.jsonc --env-interface RefreshEnv --include-runtime=false` (hash: 9f6121c46845ee56e568878caf768eb2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		STORE: R2Bucket;
		DB: D1Database;
		DISPATCH_ENABLED: "true";
		GITHUB_REPOSITORY: "heathermhuang/platehk";
		PRODUCTION_URL: "https://plate.hk";
	}
}
interface RefreshEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DISPATCH_ENABLED" | "GITHUB_REPOSITORY" | "PRODUCTION_URL">> {}
}
